AnandChowdhary/calendar-link

README.md
index.test.ts
index.ts
interfaces.ts

Hi Anand, thanks for the great library, this has saved me loads of time.
For a project I'm working on I need the ability to create all-day events. According to [these docs](https://github.com/InteractionDesignFoundation/add-event-to-calendar-docs) this is possible by using `YYYYMMDD` format for the start/end times on all of the services. I have verified that this works on Google Calendar, but I don't use any of the other services, so I'm trusting the docs that this actually works on Yahoo/Outlook...
I have also changed the timezone behavior slightly: I explicitly convert all the passed-in dates to UTC, which in my opinion is the correct behavior. I got test failures on the current master (without making any changes) because I am on UK time - I assume you are on EU time, as the times were …

✨ All-day events

---

index.test.ts
index.ts

Currently all exported ICS events are all day.
This commit follows the convention used in other format functions to check whether an event is all day before formatting the start and end times.
Fixes #78

Support non-full day events in ICS format (#1)

---

README.md
index.test.ts
index.ts
interfaces.ts
utils.ts

This allows calendar-link to be used during server-side rendering,
such as with next.js
This PR also:
* exports the CalendarEvent interface
* makes the behavior of eventify treat event as immutable
* uses more explicit types for eventify
* ran prettier over the source

Allow url to be specified explicitly to avoid document dependency

---

README.md
index.test.ts
index.ts

**Problem**
The outlook link is only creating a link to outlook.live.com — outlook's business accounts goes to outlook.office.com. 
**Solution**
The parameter syntax to live.com and office.com are the same. So I reused everything into a new variable named _office365_ and used the Outlook interface. 
**Tests**
I ran the tests with no problems. 
**Comments**
I noticed that my linter made some oneliners in the index.test.ts. I can reproduce and turn of the linter, making sure that I do not change any lines that is in reality not changed – if you prefer that.

Added support for Office365 Links

---

index.ts

Add escaping for the location field when generating ICS data and escape commas and semicolons as well as the existing newline escapes

Better escaping for ICS events

---

src/index.spec.ts
src/index.ts
src/utils.ts

Supplying a time without offset makes Outlook and Office365 assume the time is in the user's local time. But in reality the times in this case are actually converted to UTC times, hence the links created by the library are off.
I also removed the `.replace(...)` parts as we can just format the dates how we want to using day.js.
I also updated the tests for these cases so we don't use date mangling in them, because if we do the things that I changed aren't actually really tested. Let me know what you think of this.
This should fix https://github.com/AnandChowdhary/calendar-link/issues/236

[bugfix] Add offset to Outlook and Office365 times

---

package-lock.json
package.json
tsconfig.json

`index.modern.js` may be used directly in ES modules
```html
<script type="module">
import * as CalendarLink from 'https://unpkg.com/.../dist/index.modern.js';
</script>
```
`index.umd.js` may be used directly via external <script> tag
```html
<script src="https://unpkg.com/.../dist/index.umd.js"></script>
```
You can test it with my fork (it's jsdelivr because I didn't publish it to NPM, but I hope you get the idea 🙂)
https://cdn.jsdelivr.net/gh/erykpiast/calendar-link@020f3250ce652077a3561f0413159df44e6d9695/dist/index.modern.js

Add bundler to allow usage via unpkg

---

package.json

Provide a fix for #337 and #338 by
a) using relative path in `exports` field of `package.json`
b) separating ESM and CSJ exports

Fix TypeScript imports

---

src/index.ts

Yahoo calendar expects a duration parameter set to `allday` for All day events.

Handle allday for Yahoo

---

src/index.spec.ts
src/index.ts
src/interfaces.ts

This PR adds an Event Organizer key to the event configuration. This is an optional Key that, if provided, will add an ORGANIZER config to ICS files. These files, when emailed in gmail will then show the correct information rather than `Unknown Organizer` 
The organizer key is an interface with name and email, because the format of the field would be ambiguous without it. This can be simplified if needed, but is more clear as is.
Closes #404

Add event organizer and test

---

src/index.spec.ts

Bring back the tests that were removed in May.
Resolve a few issues with the expectations. One was timezone dependent, which could explain why it may have worked locally but not in a build system.

Restore tests and make them pass

---

src/index.spec.ts
src/index.ts
src/interfaces.ts
src/utils.ts

From our testing, it appears that Outlook and Office 365 will default the hour for the event based on the hour provided. 
Since the library currently converts all times to UTC, the events in these calendars are being placed at the wrong hour (unless you happen to be in the UTC timezone).
To fully support Outlook/Office365, the code needs to be changed to no longer convert to UTC but rather pass the local time without any offset in the URL.

Support local time (not UTC) for Outlook and Office365

---

src/index.spec.ts
src/index.ts

updates the link format for outlook but also added additional links for mobile apps as these still support the older format and not the new one.
Related to issue https://github.com/AnandChowdhary/calendar-link/issues/542 
I'm new to NPM but I think this makes sense to me.

Updated links for outlook calendars

---

src/index.ts

The library works perfectly with links creation, but I've found several issues when trying to create an ics file, it failed [iCalendar validation](https://icalendar.org/validator.html), so here are several suggestions that worked in my case:
- Changed \n to \r\n for the end of the line
- Added PRODID (as event name), UID (random), DTSTAMP (new Date())

Fix ics file generation (CLRF, absent fields: PRODID, UID, DTSTAMP)

---

package.json

Fixes #559
When adding this local variant to my yarn depedencies, type resolving seems to work fine again.

Add explicit types path to exports key in package.json

---

jest.config.js
package.json
src/__snapshots__/index.spec.ts.snap
src/index.spec.ts

**Description:**
This PR addresses the issues causing snapshot mismatches in the ics link generator tests. The following changes have been made to ensure the tests pass consistently:
1. **Fixed `DTSTAMP` Property:**
- Introduced a fixed system time for Jest tests using `jest.setSystemTime` and setting a constant date in a `beforeAll` block. This prevents the `DTSTAMP` property from changing with every test run.
2. **Stable `UID` Property:**
- Mocked `Math.random` to return a consistent value during tests. This ensures the `UID` property remains the same across test runs, resolving issues with snapshot testing.
3. **Consistent Line Endings:**
- Updated snapshots to use consistent line endings (`%0D%0A` for CRLF) in alignment with the changes made in PR …

Fix Snapshot Tests for ICS Links

---

src/__snapshots__/index.spec.ts.snap
src/index.spec.ts
src/index.ts
src/interfaces.ts

**Feature Description:**
This PR introduces the ability to generate links for creating Microsoft Teams calendar events using our calendar link generator package. The new feature utilizes the deep link configuration for Microsoft Teams, allowing users to easily create links that open a meeting scheduling dialog in Microsoft Teams. Resolves #598.
**Key Changes:**
1. **Microsoft Teams Event Generation:** Added functionality to generate Microsoft Teams calendar event links following the format specified in the [Microsoft Teams deep link documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-link-workflow?tabs=teamsjs-v2#deep-link-to-open-a-meeting-scheduling-dialog).
**Testing:**
- Added Microsoft Teams to the test suite.
- Added a new test to …

Add Microsoft Teams Calendar Event Generation Feature

---

README.md
package-lock.json
package.json
src/index.ts

Remove `query-string` dependency from `calendar-link`
Limit the number of dependencies to:
* improve maintainability
* reduce bundle size
Approximately 28% smaller:
```
6.54 kB: index.modern.mjs.gz
5.92 kB: index.modern.mjs.br
6.55 kB: index.umd.js.gz
5.94 kB: index.umd.js.br
```
```
4.70 kB: index.modern.mjs.gz
4.23 kB: index.modern.mjs.br
4.70 kB: index.umd.js.gz
4.25 kB: index.umd.js.br
```
In order to keep parity with previous behavior, we had to:
* Sort the keys of the object alphabetically 
* Filter out `null` and `undefined` values
* Replace `+` with `%20` in the URL to specify spaces
Apart from the filtering of `null` and `undefined` values, none of these are strictly necessary, they just made the tests pass.
* [Node.js >= …

Remove query-string dependency (28% smaller bundle size)

---

src/index.ts

Currently if you create a "point in time" event, e.g. "5pm ET on Feb 17, 2026", this library assumes it ends "now"
This is particularly problematic for events that are in the future, because the generated event will have an end that comes before start, and be rejected from certain calendars
Instead, it seems safer to assume end matches start
An alternative (possibly preferred), would be to not send `end` at all if it's not supplied. This seemed like a larger refactor though

Events without end should not necessarily end "now"

---

src/index.ts

ics `PRODID` is supposed to identify who created the ICS file. The spec format is: `-//:vendor//:product//:language`
Example from another library: https://github.com/sebbo2002/ical-generator/blob/957a2bb238e71f534bbb7c9bafb39699b30fe5e2/src/calendar.ts#L127
(and the `-` prefix is added later: https://github.com/sebbo2002/ical-generator/blob/957a2bb238e71f534bbb7c9bafb39699b30fe5e2/src/calendar.ts#L741)

Set ics PRODID correctly
